
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace LegoDimensionsReadNfc
{
    using Terminal.Gui;


    public partial class DisplayInfo
    {
        public DisplayInfo()
        {
            InitializeComponent();            
        }

        public Label Label => lblCurrentAction;

        public Button ButtonClose => btnClose;

        public TextView View => lblView;
    }
}
