
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace LegoDimensionsReadNfc {
    using System;
    using Terminal.Gui;
    
    
    public partial class DisplayInfo : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.Label lblCurrentAction;
        
        private Terminal.Gui.TextView lblView;
        
        private Terminal.Gui.Button btnClose;
        
        private void InitializeComponent() {
            this.btnClose = new Terminal.Gui.Button();
            this.lblView = new Terminal.Gui.TextView();
            this.lblCurrentAction = new Terminal.Gui.Label();
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.lblCurrentAction.Width = Dim.Fill(0);
            this.lblCurrentAction.Height = 1;
            this.lblCurrentAction.X = 0;
            this.lblCurrentAction.Y = 0;
            this.lblCurrentAction.ColorScheme = this.blueOnBlack;
            this.lblCurrentAction.Data = "lblCurrentAction";
            this.lblCurrentAction.Text = "current action";
            this.lblCurrentAction.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblCurrentAction);
            this.lblView.Width = Dim.Fill(2);
            this.lblView.Height = Dim.Fill(2);
            this.lblView.X = 0;
            this.lblView.Y = 1;
            this.lblView.AllowsTab = true;
            this.lblView.AllowsReturn = true;
            this.lblView.WordWrap = false;
            this.lblView.Data = "lblView";
            this.lblView.Text = "Heya";
            this.lblView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lblView);
            this.btnClose.Width = 9;
            this.btnClose.Height = 1;
            this.btnClose.X = Pos.AnchorEnd(11);
            this.btnClose.Y = Pos.AnchorEnd(1);
            this.btnClose.Data = "btnClose";
            this.btnClose.Text = "Close";
            this.btnClose.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnClose.IsDefault = true;
            this.Add(this.btnClose);
        }
    }
}
