#ifndef LWIPOPTS_H
#define LWIPOPTS_H

#define NO_SYS 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_DHCP 1
#define LWIP_DNS 1
#define LWIP_TCP 1
#define LWIP_UDP 1
#define LWIP_RAW 1
#define LWIP_ICMP 1
#define LWIP_IGMP 1
#define LWIP_ARP 1
#define LWIP_ETHERNET 1
#define LWIP_MDNS_RESPONDER 1
#define LWIP_CHKSUM_ALGORITHM 3
#define MEM_ALIGNMENT 4
#define MEM_SIZE 16000
#define MEMP_NUM_SYS_TIMEOUT (LWIP_NUM_SYS_TIMEOUT_INTERNAL + 4)
#define MEMP_NUM_TCP_PCB 12
#define MEMP_NUM_TCP_PCB_LISTEN 4
#define MEMP_NUM_TCP_SEG 32
#define PBUF_POOL_SIZE 24
#define TCP_MSS 1460
#define TCP_WND (4 * TCP_MSS)
#define TCP_SND_BUF (4 * TCP_MSS)
#define TCP_SND_QUEUELEN ((4 * TCP_SND_BUF + TCP_MSS - 1) / TCP_MSS)
#define TCP_QUEUE_OOSEQ 1
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_NUM_NETIF_CLIENT_DATA 1
#define LWIP_HTTPD_CGI 1
#define LWIP_HTTPD_CUSTOM_FILES 1
#define LWIP_HTTPD_DYNAMIC_HEADERS 0
#define HTTPD_FSDATA_FILE "fsdata.c"
#define LWIP_STATS 0
#define LWIP_DHCP_DOES_ACD_CHECK 0

#endif
